#!/usr/bin/env python3
"""
Generate consolidated validation report from all checks.
"""

import json
from pathlib import Path
from datetime import datetime
import os


def load_report(report_path: Path) -> dict:
    """Load a JSON report file."""
    try:
        with open(report_path, 'r') as f:
            return json.load(f)
    except Exception as e:
        return {"error": str(e), "errors": 0, "warnings": 0}


def main():
    """Generate markdown report."""
    print("📊 Generating consolidated report...")
    
    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)
    
    # Load all available reports
    report_files = {
        "structure": "structure-report/structure-report.json",
        "keyboard": "keyboard-report/keyboard-report.json",
        "security": "security-report/security-report.json",
        "compatibility": "compatibility-report/compatibility-report.json"
    }
    
    reports = {}
    for name, filename in report_files.items():
        # Try both possible paths
        path1 = reports_dir / filename
        path2 = reports_dir / filename.split('/')[0] / filename.split('/')[-1] if '/' in filename else path1
        path3 = reports_dir / filename.split('/')[-1]
        
        for path in [path1, path2, path3]:
            if path.exists():
                reports[name] = load_report(path)
                break
        else:
            reports[name] = {"errors": 0, "warnings": 0, "issues": []}
    
    # Calculate stats
    total_errors = sum(r.get("errors", 0) for r in reports.values())
    total_warnings = sum(r.get("warnings", 0) for r in reports.values())
    total_checks = len(reports)
    passed_checks = sum(1 for r in reports.values() if r.get("errors", 0) == 0)
    
    # Generate markdown
    md = []
    md.append("# 🔍 Admin System Enhancement - Validation Report\n")
    md.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}\n")
    md.append("")
    md.append("## 📊 Summary\n")
    md.append(f"| Metric | Value |")
    md.append(f"|--------|-------|")
    md.append(f"| ✅ Passed | {passed_checks}/{total_checks} |")
    md.append(f"| ❌ Errors | {total_errors} |")
    md.append(f"| ⚠️ Warnings | {total_warnings} |")
    md.append("")
    md.append(f"### Overall Status: {'✅ PASSED' if total_errors == 0 else '❌ FAILED'}\n")
    md.append("")
    md.append("---\n")
    
    # Detailed results
    md.append("## 📋 Detailed Results\n")
    
    names = {
        "structure": "📁 Structure",
        "keyboard": "⌨️ Keyboard",
        "security": "🔒 Security",
        "compatibility": "🔄 Compatibility"
    }
    
    for key, title in names.items():
        report = reports.get(key, {})
        errors = report.get("errors", 0)
        warnings = report.get("warnings", 0)
        status = "✅" if errors == 0 else "❌"
        
        md.append(f"### {title}")
        md.append(f"**Status:** {status} | **Errors:** {errors} | **Warnings:** {warnings}\n")
        
        issues = report.get("issues", [])
        if issues and len(issues) <= 5:
            for issue in issues:
                severity = "❌" if issue.get("severity") == "error" else "⚠️"
                msg = issue.get("message", "")[:60]
                md.append(f"- {severity} {msg}")
            md.append("")
    
    md.append("---\n")
    md.append("*Generated by CI/CD pipeline*")
    
    # Save report
    output_path = reports_dir / "consolidated-report.md"
    with open(output_path, 'w') as f:
        f.write('\n'.join(md))
    
    print(f"✅ Report saved: {output_path}")
    
    if total_errors > 0:
        print(f"❌ {total_errors} errors found")
        sys.exit(1)
    
    print("✅ All validations passed")


if __name__ == "__main__":
    import sys
    main()
